function Vector2(a,b){this.x=a;this.y=b}Vector2.prototype.normalize=function(){var a=Math.sqrt(this.x*this.x+this.y*this.y);0!=a&&(this.x/=a,this.y/=a);return this};Vector2.prototype.getMagnitude=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};Vector2.prototype.dot=function(a){return this.x*a.x+this.y*a.y};Vector2.prototype.add=function(a){this.x+=a.x;this.y+=a.y;return this};Vector2.prototype.subtract=function(a){this.x-=a.x;this.y-=a.y;return this};
Vector2.prototype.mul=function(a){this.x*=a.x;this.y*=a.y;return this};Vector2.prototype.multiplyByScalar=function(a){this.x*=a;this.y*=a;return this};Vector2.prototype.getRotatedBy=function(a){return new Vector2(this.x*Math.cos(a)-this.y*Math.sin(a),this.x*Math.sin(a)+this.y*Math.cos(a))};Vector2.prototype.reflect=function(a){a.multiplyByScalar(2*this.dot(a));this.subtract(a);this.normalize();return this};var LOADED_IMAGES=[];function imageLoaded(a){for(var b=0;b<LOADED_IMAGES.length;b++)if(LOADED_IMAGES[b].src===a)return b;return-1}function keepImage(a){imageLoaded(a.src)||LOADED_IMAGES.push(a)}
function GameObject(a,b,c,d,f){if(a&&!a.startsWith("#")){if(-1===imageLoaded(a)){var e=new Image;e.onload=keepImage(e);e.src="sprites/"+a;this.sprite=e}else this.sprite=LOADED_IMAGES[imageLoaded(a)];this.hasSprite=!0}else this.sprite=a,this.hasSprite=!1;this.scale=d;this.x=b;this.y=c;this.angularVelocity=this.rotation=0;this.gravity=null;this.hasMovement=this.visible=!0;this.transparency=1;this.zIndex=f||0;this.markedForDeletion=this.deleteOnViewportExit=this.wrapViewport=!1;this.acceleration=new Vector2(0,
0);this.velocity=new Vector2(0,0)}
GameObject.prototype.updatePhysics=function(a){this.hasMovement&&(this.gravity&&this.velocity.add(this.gravity.multiplyByScalar(this.gravity,a)),this.velocity.x+=this.acceleration.x*a,this.velocity.y+=this.acceleration.y*a,this.x+=this.velocity.x*a,this.y+=this.velocity.y*a);this.rotation+=this.angularVelocity*a;this.wrapViewport&&(this.getLeftBound()>=canvas.width&&(this.x=1),0>=this.getRightBound()&&(this.x=canvas.width-1),this.getTopBound()>=canvas.height&&(this.y=1),0>=this.getBottomBound()&&
(this.y=canvas.height-1));this.deleteOnViewportExit&&(this.getLeftBound()>=canvas.width&&(this.markedForDeletion=!0),0>=this.getRightBound()&&(this.markedForDeletion=!0),this.getTopBound()>=canvas.height&&(this.markedForDeletion=!0),0>=this.getBottomBound()&&(this.markedForDeletion=!0))};GameObject.prototype.update=function(){};
GameObject.prototype.render=function(){this.visible&&(ctx.globalAlpha=this.transparency,ctx.translate(this.x,this.y),ctx.rotate(this.rotation),this.hasSprite?ctx.drawImage(this.sprite,-(this.scale/2),-(this.sprite.height/this.sprite.width*this.scale/2),this.scale,this.sprite.height/this.sprite.width*this.scale):(ctx.fillStyle=this.sprite,ctx.fillRect(-this.scale/2,-this.scale/2,this.scale,this.scale)),ctx.rotate(-this.rotation),ctx.translate(-this.x,-this.y),ctx.globalAlpha=1)};
GameObject.prototype.renderExtra=function(){};GameObject.prototype.getWidth=function(){return this.scale};GameObject.prototype.getHeight=function(){return this.hasSprite&&this.sprite?this.sprite.height/this.sprite.width*this.scale:this.scale};GameObject.prototype.getLeftBound=function(){return this.x-this.getWidth()/2};GameObject.prototype.getRightBound=function(){return this.x+this.getWidth()/2};GameObject.prototype.getTopBound=function(){return this.y-this.getHeight()/2};
GameObject.prototype.getBottomBound=function(){return this.y+this.getHeight()/2};GameObject.prototype.pointCollide=function(a,b){return this.getLeftBound()<=a&&a<=this.getRightBound()&&this.getTopBound()<=b&&b<=this.getBottomBound()?!0:!1};GameObject.prototype.rectCollide=function(a){return this.getLeftBound()<=a.getRightBound()&&a.getLeftBound()<=this.getRightBound()&&this.getTopBound()<=a.getBottomBound()&&a.getTopBound()<=this.getBottomBound()?!0:!1};Particle.prototype=Object.create(GameObject.prototype);function Particle(a,b,c,d){GameObject.call(this,a,b,c,d);this.life=0;this.hasLife=!1;this.rotation=getRandomFloat(-5,5);this.deleteOnViewportExit=!0}Particle.prototype.setLife=function(a){this.life=a;this.hasLife=!0};Particle.prototype.update=function(a){this.hasLife&&(0>=this.life?this.markedForDeletion=!0:this.life-=a)};function ParticleSystem(a,b,c,d,f,e,g,h,k,l,m,n,p,q){this.x=b;this.y=c;this.lifetime=d;this.sprite=a;this.gameObjects=[];this.created=!1;this.hasLife=!0;this.numParticles=f;this.minSize=e;this.maxSize=g;this.minSpeed=h;this.maxSpeed=k;this.minX=l;this.maxX=m;this.minY=n;this.maxY=p;this.gravity=q;0==this.lifetime&&(this.hasLife=!1)}
ParticleSystem.prototype.update=function(a){this.hasLife&&(0>=this.lifetime?currentLevel.removeParticleSystem(this):this.lifetime-=a);for(a=0;a<this.gameObjects.length;a++)this.gameObjects[a]&&(this.gameObjects[a].transparency=0<this.gameObjects[a].transparency-.01?this.gameObjects[a].transparency-.01:0);if(!this.created){for(a=0;a<this.numParticles;a++){var b=new Particle(this.sprite,this.x,this.y,getRandomFloat(this.minSize,this.maxSize));b.velocity=(new Vector2(getRandomFloat(this.minX,this.maxX),
getRandomFloat(this.minY,this.maxY))).normalize();var c=getRandomFloat(this.minSpeed,this.maxSpeed);b.velocity.multiplyByScalar(c);this.gravity&&(b.gravity=this.gravity);this.gameObjects.push(b);currentLevel.addGameObject(b)}this.created=!0}};function Level(){this.gameObjects=[];this.particleSystems=[]}Level.prototype.objectCount=function(){for(var a=0,b=0;b<this.gameObjects.length;b++)this.gameObjects[b]&&a++;return a};Level.prototype.addParticleSystem=function(a){this.particleSystems.push(a);return a};
Level.prototype.removeParticleSystem=function(a){if(a=this.particleSystems.indexOf(a)){for(var b=0;b<this.particleSystems[a].gameObjects.length;b++)this.particleSystems[a].gameObjects[b]&&this.removeGameObject(this.particleSystems[a].gameObjects[b]);this.particleSystems.splice(a)}};Level.prototype.addGameObject=function(a){for(var b=!1,c=0;c<this.gameObjects.length;c++)if(!this.gameObjects[c]){this.gameObjects[c]=a;b=!0;break}b||this.gameObjects.push(a);return a};
Level.prototype.removeGameObject=function(a){(a=this.gameObjects.indexOf(a))&&this.gameObjects.splice(a)};
Level.prototype.updateObjects=function(a){this.gameObjects.sort(function(a,b){return a.zIndex-b.zIndex});if(this.gameObjects)for(var b=0;b<this.gameObjects.length;b++)this.gameObjects[b]?this.gameObjects[b].markedForDeletion?this.removeGameObject(this.gameObjects[b]):(this.gameObjects[b].updatePhysics(a),this.gameObjects[b].update(a)):this.gameObjects.splice(b,1);if(this.particleSystems)for(b=0;b<this.particleSystems.length;b++)this.particleSystems[b]&&this.particleSystems[b].update(a)};
Level.prototype.renderObjects=function(){if(this.gameObjects)for(var a=0;a<this.gameObjects.length;a++)this.gameObjects[a]&&(this.gameObjects[a].render(),this.gameObjects[a].renderExtra())};Level.prototype.unload=function(){if(this.gameObjects)for(var a=0;a<this.gameObjects.length;a++)this.gameObjects[a]&&this.removeGameObject(this.gameObjects[a]);if(this.particleSystems)for(a=0;a<this.particleSystems.length;a++)this.particleSystems[a]&&this.removeGameObject(this.particleSystems[a])};
Level.prototype.init=function(){};Level.prototype.update=function(){};Level.prototype.render=function(){};Level.prototype.onMouseDown=function(){};Level.prototype.onMouseMove=function(){};Asteroid.prototype=Object.create(GameObject.prototype);function Asteroid(a,b,c){GameObject.call(this,"asteroid.png",a,b,c);this.deleteOnViewportExit=!0}
Asteroid.prototype.processHit=function(){currentLevel.addParticleSystem(new ParticleSystem("asteroid.png",this.x,this.y,2,25,5,15,40,80,-50,50,-50,50));currentLevel.score+=Math.floor(100-this.scale);if(40<=this.scale)for(var a=0;a<getRandom(2,4);a++){var b=new Asteroid(this.x,this.y,this.scale/2);b.velocity=this.velocity.getRotatedBy(getRandomFloat(-1,1));currentLevel.asteroids.push(currentLevel.addGameObject(b))}};Ship.prototype=Object.create(GameObject.prototype);function Ship(a,b,c,d){GameObject.call(this,a,b,c,d);this.health=100;this.timeBetweenShots=.5;this.shotTimer=0;this.turnSpeed=3;this.speed=80;this.powerups=[0,0,0];this.wrapViewport=!0}Ship.prototype.removeHealth=function(a){0>=this.powerups[POWERUP_INVULNERABILITY]&&(this.health-=a);0>=this.health&&(switchLevel(new LossMenu(currentLevel.score)),this.health=-1)};
Ship.prototype.fireBullet=function(){var a=(new Vector2(Math.sin(this.rotation),-Math.cos(this.rotation))).multiplyByScalar(this.scale),b=new Bullet("#FF0000",this.x+a.x,this.y+a.y,5);b.velocity=a.normalize().multiplyByScalar(800);currentLevel.addGameObject(b);0<this.powerups[POWERUP_TRISHOT]&&(a=(new Vector2(Math.sin(this.rotation-.2),-Math.cos(this.rotation-.2))).multiplyByScalar(this.scale),b=new Bullet("#FF0000",this.x+a.x,this.y+a.y,5),b.velocity=a.normalize().multiplyByScalar(800),currentLevel.addGameObject(b),
a=(new Vector2(Math.sin(this.rotation+.2),-Math.cos(this.rotation+.2))).multiplyByScalar(this.scale),b=new Bullet("#FF0000",this.x+a.x,this.y+a.y,5),b.velocity=a.normalize().multiplyByScalar(800),currentLevel.addGameObject(b));this.shotTimer=this.timeBetweenShots;0<this.powerups[POWERUP_SHOT_SPEED]&&(this.shotTimer/=5)};
Ship.prototype.update=function(a){0<this.shotTimer&&(this.shotTimer-=a);for(var b=0;b<this.powerups.length;b++)0<this.powerups[b]&&(this.powerups[b]-=a);this.shield.x=this.x;this.shield.y=this.y;5<this.powerups[POWERUP_INVULNERABILITY]?(this.shield.visible=!0,this.shield.transparency=.4):0<this.powerups[POWERUP_INVULNERABILITY]?(this.shield.visible=!0,.4<this.shield.transparency?this.shield.incrementing=!1:.1>=this.shield.transparency&&(this.shield.incrementing=!0),this.shield.transparency+=this.shield.incrementing?
a/2:-(a/2)):this.shield.visible=!1;for(b=0;b<currentLevel.asteroids.length;b++)currentLevel.asteroids[b]&&this.rectCollide(currentLevel.asteroids[b])&&(this.removeHealth(getRandom(5,9)),currentLevel.addParticleSystem(new ParticleSystem("asteroid.png",currentLevel.asteroids[b].x,currentLevel.asteroids[b].y,2,25,5,15,40,80,-50,50,-50,50)),currentLevel.asteroids[b].markedForDeletion=!0,delete currentLevel.asteroids[b]);this.acceleration.x*=.6;this.acceleration.y*=.6;this.velocity.x*=.995;this.velocity.y*=
.995;keysDown[32]&&0>=this.shotTimer&&this.fireBullet();keysDown[68]?this.rotation+=this.turnSpeed*a:keysDown[65]&&(this.rotation-=this.turnSpeed*a);keysDown[87]?(a=(new Vector2(-Math.sin(this.rotation),Math.cos(this.rotation))).multiplyByScalar(this.scale),this.acceleration=(new Vector2(Math.sin(this.rotation),-Math.cos(this.rotation))).multiplyByScalar(this.speed),currentLevel.addParticleSystem(new ParticleSystem("fire.png",this.x+a.x,this.y+a.y,2,2,5,15,40,80,10*a.x-50,10*a.x+50,10*a.y-50,10*a.y+
50))):keysDown[83]&&(this.acceleration=(new Vector2(-Math.sin(this.rotation),Math.cos(this.rotation))).multiplyByScalar(this.speed))};Bullet.prototype=Object.create(GameObject.prototype);function Bullet(a,b,c,d){GameObject.call(this,a,b,c,d);this.deleteOnViewportExit=!0}Bullet.prototype.update=function(){for(var a=0;a<currentLevel.asteroids.length;a++)currentLevel.asteroids[a]&&this.rectCollide(currentLevel.asteroids[a])&&(this.markedForDeletion=!0,currentLevel.asteroids[a].markedForDeletion=!0,currentLevel.asteroids[a].processHit(a),currentLevel.asteroids.splice(a))};Asteroids.prototype=Object.create(Level.prototype);function Asteroids(){Level.call(this);this.asteroids=[];this.spawnTime=10;this.wavesSpawned=this.score=this.timer=0}
Asteroids.prototype.init=function(){this.background=this.addGameObject(new GameObject("#000000",canvas.width/2,canvas.height/2,canvas.height>canvas.width?canvas.height:canvas.width,-1));this.player=this.addGameObject(new Ship("ship.png",canvas.width/2,canvas.height/2,20));this.player.shield=this.addGameObject(new GameObject("#00FFFF",0,0,50,1));this.player.shield.visible=!1};Asteroids.prototype.update=function(a){0<this.timer?this.timer-=a:(this.spawnWave(),this.timer=this.spawnTime)};
Asteroids.prototype.increaseDifficulty=function(){7<this.spawnTime?this.spawnTime--:4<this.spawnTime?this.spawnTime-=.5:2<this.spawnTime&&(this.spawnTime-=.2)};Asteroids.prototype.spawnWave=function(){this.wavesSpawned+=1;this.wavesSpawned%5&&this.increaseDifficulty();50>getRandom(0,100)&&this.spawnPowerUp();for(var a=0;5>a;a++)this.spawnAsteroid()};
Asteroids.prototype.spawnPowerUp=function(){this.addGameObject(new PowerUp(getRandom(0,this.player.powerups.length),getRandom(50,canvas.width),getRandom(50,canvas.height)))};
Asteroids.prototype.spawnAsteroid=function(){var a=getRandom(0,5),b=new Asteroid(0,0,getRandom(25,75));1>=a?(b.x=0,b.y=0,b.velocity=new Vector2(getRandomFloat(10,50),getRandomFloat(10,50))):2===a?(b.x=0,b.y=canvas.height,b.velocity=new Vector2(getRandomFloat(10,50),getRandomFloat(-10,-50))):3===a?(b.x=canvas.width,b.y=canvas.height,b.velocity=new Vector2(getRandomFloat(-10,-50),getRandomFloat(-10,-50))):(b.x=canvas.width,b.y=0,b.velocity=new Vector2(getRandomFloat(-10,-50),getRandomFloat(10,50)));
b.angularVelocity=getRandomFloat(-2,2);this.asteroids.push(this.addGameObject(b))};Asteroids.prototype.render=function(){drawText("Ship health: "+this.player.health,20,20,"#00FF00");drawText("Score: "+this.score,20,32,"#00FF00");DEBUG&&(drawText("Game object buffer len: "+this.gameObjects.length,20,44,"#00FF00"),drawText("Game objects: "+this.objectCount(),20,56,"#00FF00"))};PowerUp.prototype=Object.create(GameObject.prototype);var POWERUP_TRISHOT=0,POWERUP_SHOT_SPEED=1,POWERUP_INVULNERABILITY=2;
function PowerUp(a,b,c){GameObject.call(this,this.getSpriteByType(a),b,c,30);this.type=a}PowerUp.prototype.update=function(){currentLevel.player.rectCollide(this)&&(currentLevel.addParticleSystem(new ParticleSystem("#00FFFF",this.x,this.y,2,25,5,15,40,80,-50,50,-50,50)),currentLevel.player.powerups[this.type]=15,this.markedForDeletion=!0)};PowerUp.prototype.getSpriteByType=function(a){switch(a){case 0:return"trishot.png";case 1:return"shotspeed.png";case 2:return"invulnerability.png";default:return"#00FF00"}};
StartMenu.prototype=Object.create(Level.prototype);function StartMenu(){Level.call(this);this.timer=1}
StartMenu.prototype.init=function(){this.background=this.addGameObject(new GameObject("#000000",canvas.width/2,canvas.height/2,canvas.height>canvas.width?canvas.height:canvas.width,-1));this.logo=this.addGameObject(new GameObject("logo.png",canvas.width/2,canvas.height/2-100,400,2));this.playButton=this.addGameObject(new GameObject("play.png",canvas.width/2-200,canvas.height/2,100,2));this.controlsButton=this.addGameObject(new GameObject("controls.png",canvas.width/2+200,canvas.height/2,100,2))};
StartMenu.prototype.update=function(a){0<this.timer&&(this.timer-=a);0>=this.timer&&(this.spawnAsteroid(),this.timer=1)};StartMenu.prototype.onMouseDown=function(){this.playButton.pointCollide(mousePos.x,mousePos.y)?switchLevel(new Asteroids):this.controlsButton.pointCollide(mousePos.x,mousePos.y)&&switchLevel(new ControlsMenu)};
StartMenu.prototype.spawnAsteroid=function(){var a=getRandom(0,5),b=new Particle("asteroid.png",0,0,getRandom(25,75));1>=a?(b.x=0,b.y=0,b.velocity=new Vector2(getRandomFloat(10,50),getRandomFloat(10,50))):2===a?(b.x=0,b.y=canvas.height,b.velocity=new Vector2(getRandomFloat(10,50),getRandomFloat(-10,-50))):3===a?(b.x=canvas.width,b.y=canvas.height,b.velocity=new Vector2(getRandomFloat(-10,-50),getRandomFloat(-10,-50))):(b.x=canvas.width,b.y=0,b.velocity=new Vector2(getRandomFloat(-10,-50),getRandomFloat(10,
50)));b.angularVelocity=getRandomFloat(-2,2);this.addGameObject(b)};ControlsMenu.prototype=Object.create(Level.prototype);function ControlsMenu(){Level.call(this)}
ControlsMenu.prototype.init=function(){this.background=this.addGameObject(new GameObject("#000000",canvas.width/2,canvas.height/2,canvas.height>canvas.width?canvas.height:canvas.width,-1));this.controls=this.addGameObject(new GameObject("controlsbg.png",canvas.width/2,canvas.height/2,canvas.height<canvas.width?canvas.height:canvas.width));this.backButton=this.addGameObject(new GameObject("back.png",canvas.width/2+200,canvas.height/2+200,100))};
ControlsMenu.prototype.onMouseDown=function(){this.backButton.pointCollide(mousePos.x,mousePos.y)&&switchLevel(new StartMenu)};LossMenu.prototype=Object.create(Level.prototype);function LossMenu(a){Level.call(this);this.score=a}
LossMenu.prototype.init=function(){this.background=this.addGameObject(new GameObject("#000000",canvas.width/2,canvas.height/2,canvas.height>canvas.width?canvas.height:canvas.width,-1));this.backButton=this.addGameObject(new GameObject("back.png",canvas.width/2+200,canvas.height/2+200,100))};
LossMenu.prototype.render=function(){drawText("YOUR SHIP WAS DESTROYED",canvas.width/2,canvas.height/2-200,"#00FF00","50px","Helvetica","center");drawText("FINAL SCORE: "+this.score,canvas.width/2,canvas.height/2,"#00FF00","50px","Helvetica","center")};LossMenu.prototype.onMouseDown=function(){this.backButton.pointCollide(mousePos.x,mousePos.y)&&switchLevel(new StartMenu)};var canvas=document.getElementById("game-canvas");canvas||console.log("No canvas found.");var ctx=canvas.getContext("2d");canvas.width=window.innerWidth;canvas.height=window.innerHeight;var FPS=60,DEBUG=!1,currentLevel=new StartMenu;currentLevel.init();var keysDown=[],mousePos={x:0,y:0};canvas.addEventListener("mousedown",function(a){mousePos=getLocalMousePos(canvas,a);currentLevel.onMouseDown()},!1);canvas.addEventListener("mousemove",function(a){mousePos=getLocalMousePos(canvas,a)},!1);
function getLocalMousePos(a,b){var c=a.getBoundingClientRect();return{x:(b.clientX-c.left)/(c.right-c.left)*a.width,y:(b.clientY-c.top)/(c.bottom-c.top)*a.height}}window.addEventListener("keydown",function(a){keysDown[a.keyCode]=!0;switch(a.keyCode){case 37:case 39:case 38:case 40:case 32:a.preventDefault()}},!1);window.addEventListener("keyup",function(a){keysDown[a.keyCode]=!1},!1);
function drawText(a,b,c,d,f,e,g){ctx.fillStyle=d;ctx.font=(f||"12px")+" "+(e||"Helvetica");ctx.textAlign=g||"left";ctx.textBaseline="top";ctx.fillText(a,b,c)}function getRandomFloat(a,b){return Math.random()*(b-a)+a}function getRandom(a,b){return Math.floor(Math.random()*(b-a)+a)}function switchLevel(a){currentLevel.unload();currentLevel=a;currentLevel.init()}function update(a){currentLevel.updateObjects(a);currentLevel.update(a)}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);currentLevel.renderObjects();currentLevel.render()}function main(){var a=Date.now();update((a-then)/1E3);render();then=a}var then=Date.now();setInterval(main,1E3/FPS);
